### ISSUE TITLE
XSOAR Content Pack

### ISSUE THREAD

**Issue by SteveKeller** [PaloAltoNetworks/xsoar-panos-upgrade-automation#11]
Hello

### Is your feature request related to a problem?

I am currently try to use the XSOAR content pack "PAN-OS by Palo Alto Networks",
but your PAN-OS upgrade automation looks way better to me.
I hesitate at the moment with manually installation guide, because no automatically updates of content.

### Describe the solution you'd like

Make this content an officially content pack at the marketplace.

### Describe alternatives you've considered

Manually install it with the provided installation guide or copy & paste useful content directly to XSOAR.

It would be glad you could share your opinion to this topic.

Kind Regards
Steve

**Comment by adambaumeister** [comment]
Hi @SteveKeller, apologies for the delayed response.

We do have plans to one day make it available on the marketplace but there is no ETA for this at this time as it's not directly within our control what is prioritized to be released there. I will leave this issue open as others may have similar thoughts or comments.
